nome = str (input(' Digite seu nome : '))
idade = int (input (' Digite sua idade :'))
peso = float (input (' Digite seu peso : '))
altura = float  (input (' Digite sua altura : '))
dia = int (input(' Digite o dia que você nasceu : '))
mes = int (input(' Digite o número do mês que você nasceu : '))
ano = int (input(' Digite o ano que você nasceu : '))

print (' Olá', nome,'seja bem-vindo ao mundo Python')
print (' Você possui', idade,'anos de idade,',peso,'quilos e',altura,'metros de altura.')
print (' Você nasceu no dia', dia,'/', mes,'/',ano,'correto ?')
